# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_url', models.ImageField(upload_to=b'')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
