# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 04:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 17, 21, 38, 17, 526000)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 17, 21, 38, 17, 525000)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 17, 21, 38, 17, 523000)),
        ),
    ]
