# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 22:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20160516_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 5, 16, 15, 28, 31, 17000)),
        ),
    ]
